* Game Story
** The Kal'whereever Conumdrum
*** A Dwarven Army Is Camped outside the city of Kal'Someplace.
**** A hundred years ago, the city fell.
***** The citizens of the city were beset by illusions that got worse over time.
***** Eventually the miners broke into ancient ruines deep in the heart of the city.
***** A terrible sound came from the ruins.
***** Everyone either died or fled.
****** NOTE: Presumably they fled in a hurry. If we can make it to the city, there might be phat loot.
**** General Tavarium Steelhide hired mercenary groups to help overtake the city.
***** His battered breastplate bears a griffin, which is the coat of arms of his house.
****** The party found a crypt with tombs including his coat of arms.
**** The party is tasked with finding a lost scouting group (30 men).
***** Scouts were looking for an entrance to the mines and were clearing out monsters.
***** The entrance of the catacombs was barricaded shut (?)from the outside(?).
****** This is somewhat suspicious. Did they seal their own party inside? If so, no wonder they are lost.
***** Upon entering the catacombs the party noticed the smell of food and the sound of music.
****** Following this (?)enchanted(?) most of the party members into a never ending illusionary feast.
****** An angelic looking being beams down from on high, visible to the still rational members of party.
******* Warns of a trickster demon that will do anything to be freed.
******* Refuses to help the party out of the illusionary feast unless they agree to stop the demon.
******* Agrees to grant wishes if this is done.
******* Disappears in a huge cloud of not-very-helpfulness.
****** The feast vanishes, and the party notices a large poll of chum
******* A coin is tossed in, which the chum grabs before it hits the surface
******** NOTE: Demon coin?
******* A hasty withdrawal is made
***** Party sends ground level a status update.
****** Ground level says get back to work.
***** No sign of the party has been found, goblins-come-captives didn't know they were here.
****** Said captives die in a 40 ft pit fall
***** An armory is found, appears to have been raided; only remaining items are locked down
****** Loot
******* 1000 gp / 500 pp
******* Garnet
******* Apparently Magical Amulet
******* Apparently Magical Robe
******* Apparently Magical Robe 
******* NOTE: Maybe the dwarves took this stuff, if they exist.
******* NOTE: We should try to identify the magical items before we set out. Some of us (mainly me) are quite squishy right now.
***** A giant pig is discovered, naved Gavok
****** Has a good aura, seems pretty chill
****** Says he is a king from some pla(ain/ne)s who was last seen 300 years ago.
******* NOTE: We should figure out if he meant the biome or Astral/Shadow/Whatever.
****** He isn't sure it was 300 years ago.
****** Doesn't appear to sleep.
****** Claims they made him a big pig so he wouldn't escape, was more docile.
******* NOTE: Pigs go feral really fuckin' fast.
****** It sounds like they wanted his blood.
***** A second report is made to ground level.
****** Ground level says they'll look into piggy's history, get back to work.
***** A group of goblins are found eating in a hall next to the (now freed) pig's room.
****** They are unarmed and taken by surprise; easily dealt with.
******* NOTE: Any indication that their gear was the stuff missing from the armory?
******* NOTE: Were they eating bacon? If piggy is so old, maybe he is able to heal magically and they were harvesting him.
****** The goblin dinning hall is secured, the group rests.
